server:
  port: 9090
spring:
  application:
    name: hondor

security:
  oauth2:
    resource:
#      jwk:
#        key-set-uri: http://localhost:8080/auth/realms/code/protocol/openid-connect/certs
      user-info-uri: http://localhost:8080/auth/realms/code/protocol/openid-connect/userinfo

logging:
  level:
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.netflix.zuul: INFO

zuul:
  routes:
    todo:
      path: /todo/**
      url: https://jsonplaceholder.typicode.com/todos
